name: Deploy article-website to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'article-website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --yes --cwd ./article-website
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
